build:
  maxIssues: 0
  excludeCorrectable: false
  weights: { }
  excludes:
    - '**/build/**'
    - '**/generated/**'
    - '**/composeApp/build/**'
    - '**/composeApp/generated/**'
    - '**/preview/**'
    - '**/ui/theme/Colors.kt'
    - '**/resources/**'

config:
  validation: false
  warningsAsErrors: false
  checkExhaustiveness: false
  excludes: ''

processors:
  active: true
  exclude:
    - 'DetektProgressListener'

console-reports:
  active: true
  exclude:
    - 'ProjectStatisticsReport'
    - 'ComplexityReport'
    - 'NotificationReport'

output-reports:
  active: true

comments:
  active: true

complexity:
  active: true
  CognitiveComplexMethod:
    active: false
  ComplexCondition:
    active: true
    threshold: 4
  CyclomaticComplexMethod:
    active: true
    threshold: 15
  LargeClass:
    active: true
    threshold: 600
  LongMethod:
    active: true
    threshold: 100
    ignoreAnnotated:
      - 'Composable'
      - 'Preview'
  LongParameterList:
    active: true
    functionThreshold: 10
    constructorThreshold: 10
    ignoreDefaultParameters: true
    ignoreDataClasses: true
    ignoreAnnotated:
      - 'Composable'
      - 'Preview'
  NestedBlockDepth:
    active: true
    threshold: 5
    ignoreAnnotated:
      - 'Composable'
  TooManyFunctions:
    active: true
    thresholdInFiles: 20
    thresholdInClasses: 20
    thresholdInInterfaces: 20
    ignoreAnnotatedFunctions:
      - 'Composable'

coroutines:
  active: true
  GlobalCoroutineUsage:
    active: false
  InjectDispatcher:
    active: true
    dispatcherNames:
      - 'IO'
      - 'Default'
      - 'Unconfined'
  RedundantSuspendModifier:
    active: true
  SleepInsteadOfDelay:
    active: true
  SuspendFunSwallowedCancellation:
    active: false
  SuspendFunWithCoroutineScopeReceiver:
    active: false
  SuspendFunWithFlowReturnType:
    active: true

empty-blocks:
  active: true

exceptions:
  active: true
  InstanceOfCheckForException:
    active: true
  PrintStackTrace:
    active: true
  RethrowCaughtException:
    active: true
  ReturnFromFinally:
    active: true
    ignoreLabeled: false
  SwallowedException:
    active: true
  ThrowingExceptionFromFinally:
    active: true
  ThrowingExceptionsWithoutMessageOrCause:
    active: true
  ThrowingNewInstanceOfSameException:
    active: true
  TooGenericExceptionCaught:
    active: true
    exceptionNames:
      - 'ArrayIndexOutOfBoundsException'
      - 'Error'
      - 'IllegalMonitorStateException'
      - 'NullPointerException'
      - 'IndexOutOfBoundsException'
  TooGenericExceptionThrown:
    active: true

formatting:
  active: true
  android: true
  autoCorrect: true
  BlockCommentInitialStarAlignment:
    active: true
  ChainWrapping:
    active: true
  CommentSpacing:
    active: true
  EnumEntryNameCase:
    active: true
  Filename:
    active: true
  FinalNewline:
    active: true
  ImportOrdering:
    active: true
  Indentation:
    active: true
    excludes:
      - '**/build/**'
      - '**/generated/**'
  MaximumLineLength:
    active: true
    maxLineLength: 120
    excludes:
      - '**/test/**'
      - '**/androidTest/**'
      - '**/commonTest/**'
      - '**/jvmTest/**'
      - '**/iosTest/**'
      - '**/*Test.kt'
      - '**/*Spec.kt'
  ModifierOrdering:
    active: true
  NoBlankLineBeforeRbrace:
    active: true
  NoConsecutiveBlankLines:
    active: true
  NoEmptyClassBody:
    active: true
  NoLineBreakAfterElse:
    active: true
  NoLineBreakBeforeAssignment:
    active: true
  NoMultipleSpaces:
    active: true
  NoSemicolons:
    active: true
  NoTrailingSpaces:
    active: true
  NoUnitReturn:
    active: true
  NoUnusedImports:
    active: true
  NoWildcardImports:
    active: true
  PackageName:
    active: true
  ParameterListWrapping:
    active: true
  SpacingAroundColon:
    active: true
  SpacingAroundComma:
    active: true
  SpacingAroundCurly:
    active: true
  SpacingAroundDot:
    active: true
  SpacingAroundKeyword:
    active: true
  SpacingAroundOperators:
    active: true
  SpacingAroundParens:
    active: true
  SpacingAroundRangeOperator:
    active: true
  StringTemplate:
    active: true

naming:
  active: true
  FunctionNaming:
    active: true
    ignoreAnnotated:
      - 'Composable'
      - 'Preview'
  FunctionParameterNaming:
    active: true
  VariableNaming:
    active: true
  TopLevelPropertyNaming:
    active: true
  ClassNaming:
    active: true
  ObjectPropertyNaming:
    active: true
  PackageNaming:
    active: true
  MatchingDeclarationName:
    active: false

performance:
  active: true
  ForEachOnRange:
    active: true
    excludes:
      - '**/*Composable*.*'
  SpreadOperator:
    active: true
    excludes:
      - '**/*Composable*.*'
  UnnecessaryTemporaryInstantiation:
    active: true

potential-bugs:
  active: true
  AvoidReferentialEquality:
    active: true
  DoubleMutabilityForCollection:
    active: true
  EqualsAlwaysReturnsTrueOrFalse:
    active: true
  EqualsWithHashCodeExist:
    active: true
  HasPlatformType:
    active: true
  MapGetWithNotNullAssertionOperator:
    active: true
  UnnecessaryNotNullOperator:
    active: true
  UnnecessarySafeCall:
    active: true
  UnsafeCallOnNullableType:
    active: true
  UnsafeCast:
    active: true
  UnusedUnaryOperator:
    active: true
  UselessPostfixExpression:
    active: true

style:
  active: true
  MaxLineLength:
    active: true
    excludes:
      - '**/test/**'
      - '**/androidTest/**'
      - '**/commonTest/**'
      - '**/jvmTest/**'
      - '**/iosTest/**'
      - '**/*Test.kt'
      - '**/*Spec.kt'
  MagicNumber:
    active: true
    ignoreNumbers:
      - '-1'
      - '0'
      - '1'
      - '2'
      - '100'
      - '200'
      - '400'
      - '401'
      - '403'
      - '404'
      - '500'
    excludes:
      - '**/ui/theme/Colors.kt'
      - '**/generated/**'
      - '**/*Composable*.*'
      - '**/test/**'
      - '**/androidTest/**'
      - '**/commonTest/**'
      - '**/jvmTest/**'
      - '**/iosTest/**'
      - '**/*Test.kt'
      - '**/*Spec.kt'
  FunctionOnlyReturningConstant:
    active: true
  ReturnCount:
    active: true
    max: 4
    ignoreAnnotated:
      - 'Composable'
  VarCouldBeVal:
    active: true
  UnnecessaryLet:
    active: false
  WildcardImport:
    active: false
