name: Deploy Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'README.md'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Install MkDocs (Optional, if using MkDocs)
        run: |
          pip install mkdocs-material

      - name: Build MkDocs (Optional, if using MkDocs)
        run: |
          mkdocs build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './site' # or your docs folder if not using mkdocs

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
